server:
  port: 8696
  servlet:
    context-path: /gym-pose
spring:
  rabbitmq:
    host: ${PROD_RABBITMQ_HOST}
    port: 5671
    username: ${PROD_RABBITMQ_USERNAME}
    password: ${PROD_RABBITMQ_PASSWORD}
    virtual-host: ${PROD_RABBITMQ_VIRTUAL_HOST}
    ssl:
      enabled: true
  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: ${RABBITMQ_USERNAME}
  #    password: ${RABBITMQ_PASSWORD}
  data:
    redis:
      host: ${PROD_REDIS_HOST}
      port: 6379
      password: ${PROD_REDIS_PASSWORD}
      ssl:
        enabled: true
  datasource:
    url: ${PROD_DBMS_URL}
    username: ${PROD_DBMS_USERNAME}
    password: ${PROD_DBMS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${PROD_EMAIL_USERNAME}
    password: ${PROD_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
  #logging:
  #  config: classpath:logback-spring.xml.bak
  #  file:
  #    path: ${LOG_PATH}
app:
  auth:
    access-token-secret: ${PROD_ACCESS_TOKEN_SECRET}
    access-token-expiration-msec: 7200000
    refresh-token-secret: ${PROD_REFRESH_TOKEN_SECRET}
    refresh-token-expiration-msec: 2592000000
  admin:
    email: ${PROD_ADMIN_EMAIL}
    password: ${PROD_ADMIN_PASSWORD}
    first-name: ${PROD_ADMIN_FIRST_NAME}
    last-name: ${PROD_ADMIN_LAST_NAME}
web-url: http://localhost:3000
expo-url: https://exp.host/--/api/v2/push/send
cloudinary:
  cloud-name: ${PROD_CLOUD_NAME}
  api-key: ${PROD_API_KEY}
  api-secret: ${PROD_API_SECRET}
  secure: true