server:
  port: 8696
  servlet:
    context-path: /gym-pose
spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  messages:
    basename: messages
    encoding: UTF-8
  thymeleaf:
    mode: HTML
  datasource:
    url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5433/gympose}
    username: ${DBMS_USERNAME:postgres}
    password: ${DBMS_PASSWORD:giabao123123}
    hikari:
      max-lifetime: 60000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:giabao7112004@gmail.com}
    password: ${EMAIL_PASSWORD:gisb quje jpua taef}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
#logging:
#  config: classpath:logback-spring.xml.bak
#  file:
#    path: ${LOG_PATH}
app:
  auth:
    access-token-secret: ${ACCESS_TOKEN_SECRET:Ckj2tdZqqx4zYqn0iSB9bUPIsckWdFoa/YIi1kzGWKc9qM5XCbRoPHmWhft9pZZCGeKYcAhgILzOu++4toDC0Gn9iDWTlRAlnQ8efRnVU8I=}
    access-token-expiration-msec: 7200000
    refresh-token-secret: ${REFRESH_TOKEN_SECRET:iq6GbB4ypM4UvmGQTu6fD+7IJvD07edYE/dyNOWO+23t6trHtj2QZ13U+YHDLOsdmIwDTVhTQOF5c3yHxDCKaw==4}
    refresh-token-expiration-msec: 2592000000
  admin:
    email: ${ADMIN_EMAIL:giabao7112004@gmail.com}
    password: ${ADMIN_PASSWORD:giabao123123}
    first-name: ${ADMIN_FIRST_NAME:ADMIN}
    last-name: ${ADMIN_LAST_NAME:SYSTEM}
web-url: http://localhost:3000