server:
  servlet:
    context-path: /gym-pose
  port: 8696
spring:
  thymeleaf:
    mode: HTML
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
    hikari:
      max-lifetime: 60000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
logging:
  config: classpath:logback-spring.xml
  file:
    path: ${LOG_PATH}
app:
  auth:
    access-token-secret: 928d4aef-6452-4ca1-8e4e-7dabad510423
    access-token-expiration-msec: 7200000
    refresh-token-secret: cf427568-e272-4d5d-8195-18cc8bcbd0c4
    refresh-token-expiration-msec: 2592000000
